FROM openjdk:8-jre-alpine3.8
RUN mkdir /opt/ves-agent && chmod 777 -R /opt/ves-agent
VOLUME /tmp
ARG JAR_FILE
ARG PROPERTIES_FILE
COPY ${PROPERTIES_FILE} /opt/ves-agent/config.properties
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
